#pragma once

#define FRTC_SDK_VERSION_MAJOR  3
#define FRTC_SDK_VERSION_MAJOR2 4
#define FRTC_SDK_VERSION_MINOR  0
#define FRTC_SDK_VERSION_MINOR2 0

#define TO_STRING_POUND(arg) #arg
#define TO_STRING(arg) TO_STRING_POUND(arg)
#define FRTC_SDK_FULL_VERSION TO_STRING(FRTC_SDK_VERSION_MAJOR) "." TO_STRING(FRTC_SDK_VERSION_MAJOR2) "." TO_STRING(FRTC_SDK_VERSION_MINOR)
